### ISSUE TITLE
Does not see all installed UWP apps

### ISSUE THREAD

**Issue by Jdbye** [Alia5/GloSC#104] opened 2020-02-20 03:28 UTC
GloSC doesn't see all of the games I have installed. One game that doesn't show up is Subnautica.
App ID: UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_bh1f6rvenfkm2!App

I'm not sure why that would be, as UWPHook sees them all fine. Maybe have a look at the code and see if you can figure out what it does differently, it's open source: https://briano.dev/UWPHook/

Currently, I have GloSC set up to launch UWPHook, then UWPHook launches Subnautica.
This means I have to set up the launch parameters manually for each problem game. I have just been creating a Steam library shortcut for the games using UWPHook, then copying the launch parameters from the created shortcut into GloSC and creating another shortcut, and removing the first one. This works just fine, but needless to say, it's a hassle doing this for every game.

It would be great if you could fix this issue. GloSC is exactly what I was looking for, and other than that issue, it works very well. 

Also, another small thing, it doesn't add the game icon to the Steam library shortcut and I can't figure out how to add it myself, as I can't access the app files (I can open the game folder, and there is an exe in there with an icon, I just can't get read access to any of the files, so it does me no good)
UWPHook adds a high res icon to the shortcut automatically, so it should be possible to implement in GloSC as well.

With those two features added, this would be better than UWPHook in every way.

**Comment by Thracky** [comment] 2020-03-04 14:53
The UWP game list was solved with pull request #89 but a new build isn't yet available in the main project. (It will be soon)

For now it’s available at https://github.com/Thracky/GloSC/releases/tag/2.0.7

The icon thing I'll look into.

**Comment by Deathnovan** [comment] 2020-03-04 15:26
@Thracky, Could you please validate the release in the previous link? My antivirus software is blocking it and marking it as infected with a trojan/ransomware

**Comment by Thracky** [comment] 2020-03-05 00:24
@Deathnovan I've confirmed that the sha256 hash of the build directly from the build system (Appveyor) is 42393cbcadc9f4a3fc04fe8fc8470ed5518fe0e05c27e5ab26407f995716614e which matches what I've downloaded from my Releases page. AVs are unfortunately prone to a lot of false positives based on behavioural detection.

**Comment by Deathnovan** [comment] 2020-03-05 00:33
@Thracky , Thanks for checking :).

**Comment by petetnt** [comment] 2020-03-16 23:38
Yep, same thing happened to me, marked as `Behavior:Win32/DefenseEvasion.LS!ml` mid-game 🤷‍♂

**Comment by Orinion** [comment] 2020-05-07 20:37
i reported the file as a false positive to microsoft, it should not be detected annymore :)

**Comment by petetnt** [comment] 2020-05-07 20:43
Nice, thank you!

**Comment by Skyyblaze** [comment] 2020-06-12 21:02
> 
> 
> The UWP game list was solved with pull request #89 but a new build isn't yet available in the main project. (It will be soon)
> 
> For now it’s available at https://github.com/Thracky/GloSC/releases/tag/2.0.7
> 
> The icon thing I'll look into.

Interestingly enough even this build won't detect PSO2 NA for me.

**Comment by angryansari** [comment] 2020-09-27 16:28
the issue still persists on 2.0.7 , none of the games from the xbox game pass are detected.

Microsoft.Chelan_8wekyb3d8bbwe!HaloMCCShipping
ParadoxInteractive.ProjectTitus_zfnrdv2de78ny!App

**Comment by Thracky** [comment] 2020-10-02 13:47
> the issue still persists on 2.0.7 , none of the games from the xbox game pass are detected.
> 
> Microsoft.Chelan_8wekyb3d8bbwe!HaloMCCShipping
> ParadoxInteractive.ProjectTitus_zfnrdv2de78ny!App

Completely removed any version I had installed previously, ran my installer for 2.0.7, and I see all the Xbox Game Pass games show up without issue.

![image](https://user-images.githubusercontent.com/2881908/94930203-1477d280-0494-11eb-9e1e-05a8a80df365.png)

In that screenshot, Wasteland 3, No Man's Sky, Fallout 76, and Crusader Kings 3 (Which you mentioned above) are all present.

**Comment by nonplayer** [comment] 2020-10-09 03:06
@Thracky my dude, I don't know what magic you worked here, but this update changed _everything_ for me, for the better. For the last few months I've been unable to use Glosc, either official or your fork, due to it only showing a Glosc logo and nothing else. This update fixed not only that, but _also_ the whole "glosc loads behind the game" issue that was previously forcing me to alt-tab every time I wanted to go into the steam menu. Hot damn. Thank you!

**Comment by Thracky** [comment] 2020-10-09 23:19
> @Thracky my dude, I don't know what magic you worked here, but this update changed _everything_ for me, for the better. For the last few months I've been unable to use Glosc, either official or your fork, due to it only showing a Glosc logo and nothing else. This update fixed not only that, but _also_ the whole "glosc loads behind the game" issue that was previously forcing me to alt-tab every time I wanted to go into the steam menu. Hot damn. Thank you!

I don’t really have any explanation as to why this version may have fixed all that for you as I literally changed one tiny line of code related to populating the list of UWP apps. But glad it’s working regardless!

**Comment by Thracky** [comment] 2020-10-09 23:20
Closing as this is technically “solved” at this point.

**Closed by Thracky** 2020-10-09 23:20 UTC
Labels: enhancement

**Comment by Mythol98** [comment] 2020-10-16 20:05
hey guys, i tried this version and the 2.0.6 too..  im trying to play Genshin Impact with the steam controller, but noooothing works,  someone can help me??
