### ISSUE TITLE
Not all UWP apps detected

### ISSUE THREAD

**Issue by goigle** [Alia5/GloSC#119] opened 2020-10-11 00:52 UTC
- Windows 10 x64 v2004
- Fresh install of GloSC
- GamePass games installed via Xbox App (still shows up in store as well)

GloSC is only detecting some Microsoft apps and Candy Crush and some Adobe utilities when I hit UWP. I restarted to see if that would fix it, that didn't. [UWPHook](https://github.com/BrianLima/UWPHook) is correctly loading the full app list, and I've checked the unknown app's appID to make sure it isn't just a title issue.  Probably something fun with a windows update

**Comment by Thracky** [comment] 2020-10-11 01:50
Duplicate of #104 

My latest build here resolves UWP games not showing up: https://github.com/Thracky/GloSC/releases/tag/2.0.8

**Closed by Thracky** 2020-10-11 01:50 UTC

**Comment by goigle** [comment] 2020-10-11 01:56
Perfect, thanks, sorry that I missed the other issue!

>
